name: water
favicon: null
layout_spectrum: 0.183277
typography_spectrum: 0.773649
title: water
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0C8A8'
    - '#102818'
    - '#487868'
    - '#B8C888'
    - '#C8E0B0'
  brandStrength: 0.8230061787734584
  lightness: 0.3592146352600186
  saturation: 0.10642818817133304
  rhythmicContrast: 0.6411178679069455
purpose:
  - name: null
    item: null
    url: null
